### ISSUE TITLE
Prompt

### ISSUE THREAD

**Issue by SenseiRemy** [thesacredmoocow/g14control-r2#1]
I made the task in task schedular but it is still giving me a UAC prompt. Also on low-speed fan, my fans will ramp up and then quiet down repeatedly. Suggestions?

**Comment by thesacredmoocow** [comment]
checked "run at highest privledges"?

and I noticed that the idle temps roughly hover around 49~50c, so you can mitigate that by setting 40c fan speeds and 50c fan speeds to be the same, either 5% or 10% is reccomended.

**Comment by SenseiRemy** [comment]
It is checked at highest privilege. Do I need to enable it in the config?

**Comment by thesacredmoocow** [comment]
enable what? and I think the prompt is just a biproduct of needing to change registry settings for the power plan. you can disable them in windows but not reccommended.

**Comment by bloodmage0** [comment]
Set "start_on_boot" to false to prevent launching the program with the UAC prompt.

Then at task scheduler, trigger: at logon of any user. Action: Point the path directly to the .exe instead of cmd. Leave arguments and "start in" fields empty. Keep running at the highest privilege and uncheck the start only on ac power settings. 

Edit: The fan speed ramping is something that was also an issue in Atrofac (the base program for the fan control). I don't know what causes it but sleeping the system and waking it back up would normally fix it for me.

Thanks for the release though! It works great.

**Comment by SenseiRemy** [comment]
Yep that fixed it. Thanks.
